name: almonafs_flutter
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  dio: ^5.9.0
  flutter_bloc: ^9.1.1
  get_it: ^8.2.0
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.5.3
  flutter_native_splash: ^2.4.6
  google_fonts: ^6.3.1
  flutter_screenutil: ^5.9.3

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  shimmer_animation: ^2.2.2+1
  dartz: ^0.10.1
  cached_network_image: ^3.4.1
  skeletonizer: ^2.1.0+1
  flutter_svg: ^2.2.1
  url_launcher: ^6.3.2
  intl: ^0.20.2
  font_awesome_flutter: ^10.12.0
  curved_navigation_bar: 1.0.6
  flutter_rating_bar: ^4.0.1
  flutter_html: ^3.0.0
  crystal_navigation_bar: ^1.1.0
  glass_nav_bar: ^0.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true
  assets:
    - assets/splash/
    - assets/svg/images/
    - assets/fonts/poppins/
    - assets/images/
    - assets/icons/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/splash/main_logo.png"
  remove_alpha_ios: true
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/splash/main_logo.png"
